# Generated by Django 3.0.8 on 2020-08-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnomad',
            name='transcript_id',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
