# Generated by Django 3.0.8 on 2020-08-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='gene',
            name='cdna_seq',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='name',
        ),
    ]
