# Generated by Django 3.0.8 on 2020-08-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_gnomad_transcript_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensemble',
            name='gene_name',
        ),
    ]
