# Generated by Django 3.0.8 on 2020-08-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0003_remove_ensemble_gene_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='transcript',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
