# Generated by Django 3.0.8 on 2020-08-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0004_ensemble_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='gene_name',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
